name = "stmicro"
version = "0.1.0"
[dependencies]
jsl = { git = "JITx-Inc/jsl", version = "0.4.0" }
ethernet_io_lib = { git = "JITx-Inc/ethernet_io_lib", version="0.1.1"}
JITX = { path = "{SLM_ROOT}/JITX" }
